name: Github Actions env bug

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
        - dev
        - prd
    steps:
      - name: Check CLI
        run: |
          jq --version
      - name: Prepare env-specific parameters
        run: |
          JQ_PARAMS="-r -c -M ."
          JQ_ADD_PARAMS="-s -r -c"
          common_params=$(jq ${JQ_PARAMS} <<-JSON
          {
            "variable": "true"
          }
          JSON
          )
          env_params=$(jq ${JQ_PARAMS} <<-JSON
          {
            "ENV": "${{ vars.MY_ENV }}"
          }
          JSON
          )
          env_params=$(echo "${common_params} ${env_params}" | jq ${JQ_ADD_PARAMS} add)

          echo "common_params=${common_params}" >> $GITHUB_OUTPUT
          echo "env_params=${env_params}" >> $GITHUB_OUTPUT

  bug:
    runs-on: ubuntu-latest
    needs:
    - setup
    strategy:
      matrix:
        env:
        - dev
        - prd
    steps:
      - name: Print env outputs
        run: |
          echo "Common Params:"
          echo "${{ needs.setup.outputs.common_params }}"
          echo "Env Params:"
          echo "${{ needs.setup.outputs.env_params }}"
