name: Build and use matrix
on: workflow_dispatch
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  generate-outputs:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}
    steps:
      - name: Create outputs
        id: step1
        run: echo "output_from_${{ matrix.project }}_${{ matrix.config }}=${{ matrix.project }}_${{ matrix.config }}" >> outputs.txt
      - name: Set outputs
        id: step2
        run: |
          outputs=$(cat outputs.txt)
          echo "outputs=$outputs" >> $GITHUB_OUTPUT
    outputs:
      outputs: ${{ steps.step2.outputs.outputs }}
  print-outputs:
    needs: generate-outputs
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-outputs.outputs.outputs) }}
    steps:
      - name: Print outputs generated in previous step
        run: echo "${{ matrix }}"